//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalProject.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PortalProject.Web.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string Anasayfa {
            get {
                return ResourceManager.GetString("Anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soru, öneri, istek ve şikayetlerinizi bizlere bu formu kullanarak hızlı bir şekilde iletebilirsiniz. En kısa sürede uzmanlarımız sizlere dönüş yapacaktır..
        /// </summary>
        public static string AnasayfaFormAciklama {
            get {
                return ResourceManager.GetString("AnasayfaFormAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfaya Dön.
        /// </summary>
        public static string AnasayfayaDon {
            get {
                return ResourceManager.GetString("AnasayfayaDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bize Yazın.
        /// </summary>
        public static string BizeYazin {
            get {
                return ResourceManager.GetString("BizeYazin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bizi Arayın.
        /// </summary>
        public static string BiziArayin {
            get {
                return ResourceManager.GetString("BiziArayin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulunduğunuz Şehir.
        /// </summary>
        public static string BulundugunuzSehir {
            get {
                return ResourceManager.GetString("BulundugunuzSehir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışma Saatleri.
        /// </summary>
        public static string CalismaSaatleri {
            get {
                return ResourceManager.GetString("CalismaSaatleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalıştığınız Kurum.
        /// </summary>
        public static string CalistiginizKurum {
            get {
                return ResourceManager.GetString("CalistiginizKurum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çarşamba.
        /// </summary>
        public static string Carsamba {
            get {
                return ResourceManager.GetString("Carsamba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuma.
        /// </summary>
        public static string Cuma {
            get {
                return ResourceManager.GetString("Cuma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumartesi.
        /// </summary>
        public static string Cumartesi {
            get {
                return ResourceManager.GetString("Cumartesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daha Fazla Soru.
        /// </summary>
        public static string DahaFazlaSoru {
            get {
                return ResourceManager.GetString("DahaFazlaSoru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaylar.
        /// </summary>
        public static string Detaylar {
            get {
                return ResourceManager.GetString("Detaylar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detayları Gör.
        /// </summary>
        public static string DetaylariGor {
            get {
                return ResourceManager.GetString("DetaylariGor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devamını Oku.
        /// </summary>
        public static string DevaminiOku {
            get {
                return ResourceManager.GetString("DevaminiOku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diğer - belirtiniz..
        /// </summary>
        public static string DigerBelirt {
            get {
                return ResourceManager.GetString("DigerBelirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diğer Haberler.
        /// </summary>
        public static string DigerHaberler {
            get {
                return ResourceManager.GetString("DigerHaberler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Dil {
            get {
                return ResourceManager.GetString("Dil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elektrikli Araç (EA).
        /// </summary>
        public static string EA {
            get {
                return ResourceManager.GetString("EA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content/images/eagiris.jpg.
        /// </summary>
        public static string EAGirisLogo {
            get {
                return ResourceManager.GetString("EAGirisLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EA.
        /// </summary>
        public static string EAKisa {
            get {
                return ResourceManager.GetString("EAKisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aşağıdaki formu kullanarak bize eğitim talebinizi iletebilirsiniz..
        /// </summary>
        public static string EgitimTalepFormBilgi {
            get {
                return ResourceManager.GetString("EgitimTalepFormBilgi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail Adresi.
        /// </summary>
        public static string EMailAdresi {
            get {
                return ResourceManager.GetString("EMailAdresi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content/images/logo-footer.png.
        /// </summary>
        public static string FooterLogo {
            get {
                return ResourceManager.GetString("FooterLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bizleri sosyal medya hesaplarımızdan takip ederek, tüm gelişmelerden haberdar olabilirsiniz..
        /// </summary>
        public static string FooterSosyalMedyaMesaj {
            get {
                return ResourceManager.GetString("FooterSosyalMedyaMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galeri.
        /// </summary>
        public static string Galeri {
            get {
                return ResourceManager.GetString("Galeri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        public static string Gonder {
            get {
                return ResourceManager.GetString("Gonder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haberler.
        /// </summary>
        public static string Haberler {
            get {
                return ResourceManager.GetString("Haberler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hacettepe Teknoloji AR-GE Merkezi.
        /// </summary>
        public static string HacettepeTargem {
            get {
                return ResourceManager.GetString("HacettepeTargem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        public static string Hakkimizda {
            get {
                return ResourceManager.GetString("Hakkimizda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harita.
        /// </summary>
        public static string Harita {
            get {
                return ResourceManager.GetString("Harita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Her Hakkı Saklıdır..
        /// </summary>
        public static string HerHakkiSaklidir {
            get {
                return ResourceManager.GetString("HerHakkiSaklidir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hizmetlerimiz.
        /// </summary>
        public static string Hizmetlerimiz {
            get {
                return ResourceManager.GetString("Hizmetlerimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İnsansız Hava Aracı (İHA).
        /// </summary>
        public static string IHA {
            get {
                return ResourceManager.GetString("IHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İHA Eğitimi Talep Formu.
        /// </summary>
        public static string IHAEgitimTalepFormu {
            get {
                return ResourceManager.GetString("IHAEgitimTalepFormu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content/images/ihagiris.jpg.
        /// </summary>
        public static string IHAGirisLogo {
            get {
                return ResourceManager.GetString("IHAGirisLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İnsansız Hava Aracı ihtiyaçlarınız için doğru adrestesiniz..
        /// </summary>
        public static string IHAIhtiyac {
            get {
                return ResourceManager.GetString("IHAIhtiyac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İHA.
        /// </summary>
        public static string IHAKisa {
            get {
                return ResourceManager.GetString("IHAKisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string Iletisim {
            get {
                return ResourceManager.GetString("Iletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İLETİŞİM BİLGİLERİ.
        /// </summary>
        public static string IletisimBilgileri {
            get {
                return ResourceManager.GetString("IletisimBilgileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Bilgileri.
        /// </summary>
        public static string İletisimBilgileriCap {
            get {
                return ResourceManager.GetString("İletisimBilgileriCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İLETİŞİM FORMU.
        /// </summary>
        public static string IletisimFormu {
            get {
                return ResourceManager.GetString("IletisimFormu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aşağıdaki formu kullanarak bize mesajınızı iletebilirsiniz..
        /// </summary>
        public static string IletisimSayfaForm {
            get {
                return ResourceManager.GetString("IletisimSayfaForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim.
        /// </summary>
        public static string Isim {
            get {
                return ResourceManager.GetString("Isim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim Soyisim.
        /// </summary>
        public static string IsimSoyisim {
            get {
                return ResourceManager.GetString("IsimSoyisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAPALI.
        /// </summary>
        public static string Kapali {
            get {
                return ResourceManager.GetString("Kapali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurumsal.
        /// </summary>
        public static string Kurumsal {
            get {
                return ResourceManager.GetString("Kurumsal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content/images/logo.png.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj.
        /// </summary>
        public static string Mesaj {
            get {
                return ResourceManager.GetString("Mesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pazar.
        /// </summary>
        public static string Pazar {
            get {
                return ResourceManager.GetString("Pazar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pazartesi.
        /// </summary>
        public static string Pazartesi {
            get {
                return ResourceManager.GetString("Pazartesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perşembe.
        /// </summary>
        public static string Persembe {
            get {
                return ResourceManager.GetString("Persembe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salı.
        /// </summary>
        public static string Sali {
            get {
                return ResourceManager.GetString("Sali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sayfa.
        /// </summary>
        public static string Sayfa {
            get {
                return ResourceManager.GetString("Sayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şehir Diğer İse Belirtiniz.
        /// </summary>
        public static string SehirDigerIse {
            get {
                return ResourceManager.GetString("SehirDigerIse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sık Sorulan Sorular.
        /// </summary>
        public static string SikSorulanSorular {
            get {
                return ResourceManager.GetString("SikSorulanSorular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şişirilebilir İHA.
        /// </summary>
        public static string SisirilebilirIHA {
            get {
                return ResourceManager.GetString("SisirilebilirIHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyisim.
        /// </summary>
        public static string Soyisim {
            get {
                return ResourceManager.GetString("Soyisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSS.
        /// </summary>
        public static string SSS {
            get {
                return ResourceManager.GetString("SSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talep İletiliyor....
        /// </summary>
        public static string TalepIletiliyor {
            get {
                return ResourceManager.GetString("TalepIletiliyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tarafından oluşturuldu..
        /// </summary>
        public static string TarafindanOlusturuldu {
            get {
                return ResourceManager.GetString("TarafindanOlusturuldu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih.
        /// </summary>
        public static string Tarih {
            get {
                return ResourceManager.GetString("Tarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih Diğer İse Belirtiniz.
        /// </summary>
        public static string TarihDigerIse {
            get {
                return ResourceManager.GetString("TarihDigerIse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Telefon {
            get {
                return ResourceManager.GetString("Telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Albümleri Gör.
        /// </summary>
        public static string TumAlbumleriGor {
            get {
                return ResourceManager.GetString("TumAlbumleriGor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ünvanınız.
        /// </summary>
        public static string Unvan {
            get {
                return ResourceManager.GetString("Unvan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vizyon &amp; Misyon.
        /// </summary>
        public static string VizyonMisyon {
            get {
                return ResourceManager.GetString("VizyonMisyon", resourceCulture);
            }
        }
    }
}
